server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # C'est ici que la magie opère
    location /api/ {
        # 'spring_api' est le nom de ton service dans docker-compose
        proxy_pass http://spring_api:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}